---

# Add sensors to check for updates
# https://github.com/basbruss/UI/blob/main/custom_cards/custom_card_homeassistant_updates/README.md
# TODO: add update sensor
- platform: command_line
  name: core_updates
  command: 'curl http://supervisor/core/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
  value_template: '{{ value_json.update_available }}'
  scan_interval: 600
  json_attributes:
    - update_available
    - latest_version
    - installed_version

- platform: command_line
  name: addons_updates
  command: 'curl http://supervisor/addons -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"addons":[.data.addons[] | select(.update_available)]}'''
  value_template: '{{ value_json.addons | length }}'
  scan_interval: 600
  unit_of_measurement: pending update(s)
  json_attributes:
    - addons
